---
- name: install tomcat
  package:
    name: tomcat
    state: latest

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_path }}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: templates/index.html.j2
    dest: "{{ tomcat_path }}/index.html"
    mode: 0644

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes

